### ISSUE TITLE
NullPointerException on ANotB

### ISSUE THREAD

**Issue by mix74rus** [apache/datasketches-java#368]
```java
IntegerSketch x = new IntegerSketch(12, 2, 0.1f, IntegerSummary.Mode.Min);
IntegerSketch y = new IntegerSketch(12, 2, 0.1f, IntegerSummary.Mode.Min);
x.update(1L, 1);
IntegerSummarySetOperations setOperations = new IntegerSummarySetOperations(IntegerSummary.Mode.Min, IntegerSummary.Mode.Min);
Intersection<IntegerSummary> intersection = new Intersection<>(setOperations);
CompactSketch<IntegerSummary> intersect = intersection.intersect(x, y);
AnotB.aNotB(x, intersect); // NPE here
```

```
java.lang.NullPointerException
	at org.apache.datasketches.HashOperations.hashArrayInsert(HashOperations.java:170)
	at org.apache.datasketches.HashOperations.convertToHashTable(HashOperations.java:341)
	at org.apache.datasketches.tuple.AnotB.getResultArraysTuple(AnotB.java:357)
	at org.apache.datasketches.tuple.AnotB.aNotB(AnotB.java:255)
```

**Comment by mix74rus** [comment]
> Can you let us know what release version this was (or if it was current main branch)?

Currently i'm using 2.0.0 release version and example was tested with version too. But looks like this would also reproduce in master.

**Comment by leerho** [comment]
This bug should be considered fixed and is currently in master awaiting the next release.
