### ISSUE TITLE
Possible corruption: PreLongs must be 1 or 2: 34

### ISSUE THREAD

**Issue by hqx871** [apache/datasketches-java#399]
hi team, I am a druid user and happen to get below problem.  What should cause this?
```
org.apache.datasketches.SketchesArgumentException: Possible corruption: PreLongs must be 1 or 2: 34
	at org.apache.datasketches.quantiles.DirectUpdateDoublesSketchR.checkPreLongs(DirectUpdateDoublesSketchR.java:225) ~[datasketches-java-1.3.0-incubating.jar:?]
	at org.apache.datasketches.quantiles.DirectCompactDoublesSketch.wrapInstance(DirectCompactDoublesSketch.java:150) ~[datasketches-java-1.3.0-incubating.jar:?]
	at org.apache.datasketches.quantiles.DoublesSketch.wrap(DoublesSketch.java:196) ~[datasketches-java-1.3.0-incubating.jar:?]
```

**Comment by leerho** [comment]
The sketch image has been corrupted.
