### ISSUE TITLE
ArrayIndexOutOfBounds & NullPointerException in ReversePurgeItemHashMap

### ISSUE THREAD

**Issue by SeanCherngTW** [apache/datasketches-java#426]
Hi all,

I am using `datasketches-java 2.0.0` and Java 17.0.2
I encounter some ArrayIndexOutOfBounds and NullPointerException when using ReversePurgeItemHashMap

In my use case, my system is calling
`freq.getLowerBound(term)  // freq is ItemsSketch` 
with high qps every 5 minutes. 

Then, when reaching line 332
https://github.com/apache/datasketches-java/blob/7cda6ed20ca63ff1ff7164d9c7af641cace2deed/src/main/java/org/apache/datasketches/frequencies/ReversePurgeItemHashMap.java#L329-L336
I occasionally (~1 time/day) encounter the following error:
```
java.lang.ArrayIndexOutOfBoundsException: Index 63717 out of bounds for length 32768
	at org.apache.datasketches.frequencies.ReversePurgeItemHashMap.hashProbe(ReversePurgeItemHashMap.java:332)
	at org.apache.datasketches.frequencies.ReversePurgeItemHashMap.get(ReversePurgeItemHashMap.java:85)
	at org.apache.datasketches.frequencies.ItemsSketch.getLowerBound(ItemsSketch.java:346)
```
or
```
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "this.keys[probe]" is null
	at org.apache.datasketches.frequencies.ReversePurgeItemHashMap.hashProbe(ReversePurgeItemHashMap.java:332)
	at org.apache.datasketches.frequencies.ReversePurgeItemHashMap.get(ReversePurgeItemHashMap.java:85)
	at org.apache.datasketches.frequencies.ItemsSketch.getLowerBound(ItemsSketch.java:346)
```

This error is unable to be reproduced, so I apologize that I cannot provide more context now.
Do you have any idea on this error or have you encountered a similar problem before?
thank you

**Comment by AlexanderSaydakov** [comment]
Is there a chance that you run this in a multithreaded environment? The library is not thread-safe.

**Comment by SeanCherngTW** [comment]
hi Alexander, 
thank you for the hint! Yes it's possible to run in multithreaded in our system
I think we found the root cause and I will close the issue once we verify our guess
